### ISSUE TITLE
yaml schema for the config file

### ISSUE THREAD

**Issue by staabm** [Smile-SA/gdpr-dump#106]
**Is your feature request related to a problem? Please describe.**

working out a proper configuration file takes a lot of time.
especially when importing from a big dump, a gdpr-dump might run mintes/hours and finally runs into a error like
`Unknown format "bank"`

```
mstaab@mst22:/cluster/www/www/www/gdpr-dump$ time ../gdpr-dump.phar config.yaml  > gdpr-dumped.sql.bz2
Unknown format "bank"

real    4m29.069s
user    4m27.696s
sys     0m1.067s
```

**Describe the solution you'd like**

if there would be a yaml schema for the configuration format, the gdpr-dump could sanity check the config file before starting the likely long running process of anonymizing data and errors could therefore be emitted immediately

**Describe alternatives you've considered**
none

**Additional context**

**Comment by guvra** [comment]
Hi,

Maybe we could add a check on faker converters before the start of the dump, to check if the formatter exists. This would prevent this kind of errors.

**Comment by guvra** [comment]
> a check for faker would also be possible, but that solution would not support other converters.
> 
> if we would have a "full schema" the config file could also be validated whether other converters or yaml parameters are valid

There is already a schema file (https://github.com/Smile-SA/gdpr-dump/blob/main/app/config/schema.json).
It doesn't include a list of available converters, but there is no need for this, because the converters are resolved before the start of the dump.

The only exception is the faker converter, it resolves the formatter during the dump process, on value conversion (https://github.com/Smile-SA/gdpr-dump/blob/main/src/Converter/Proxy/Faker.php#L57).
