### ISSUE TITLE
Capability to add or override faker providers

### ISSUE THREAD

**Issue by bertrand-leroux** [Smile-SA/gdpr-dump#56]
**What is the problem?**
`\Faker\Provider\Internet::userName` could easily return same value (`\Faker\Provider\Internet::$userNameFormats` are too weak) while `username` should be unique for systems with login by username
The [faker documentation](https://fakerphp.github.io/#faker-internals-understanding-providers) explains how to add our own providers, but the `\Smile\GdprDump\Faker\FakerService` does not seem to manage this override. 

**Alternatives considered**
Get some faker config to permit overrides

**Comment by guvra** [comment]
Hi @bertrand-leroux !

The faker library was added to the project so that existing Faker formatters can be used.
For custom formatters, you can create gdpr converters.
The [documentation](https://github.com/Smile-SA/gdpr-dump/blob/master/docs/04-phar.md) explains how to build a phar file that includes custom converters.

I don't think it's possible to override a Faker formatter anyway. Adding a new provider with the "username" function does not seem to work.
