### ISSUE TITLE
Postgres SQL

### ISSUE THREAD

**Issue by ColonelMoutarde** [Smile-SA/gdpr-dump#70]
Hi, the support of PostgreSql is in roadmap ? If yes when ?

Thank You

Luc an old "Smilien"

**Comment by guvra** [comment]
Hi ex-coworker :smile:,

It is not currently planned, because this tool relies on a package that is only compatible with MySQL (ifsnop/mysqldump-php).
Also, if I recall correctly, postgresql dumps are very different from dump files created by mysqldump.

We could only add postgresql support if we stopped relying on the mysqldump-php package, and implement a custom dump engine instead.

**Comment by ColonelMoutarde** [comment]
The package ifsnop/mysqldump is in end if life since 2020. 😭 🤔

**Comment by guvra** [comment]
It's working fine currently, we'll fork it if there is a major issue.
