### ISSUE TITLE
ERROR 1064 (42000) at line 27: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"table_name"

### ISSUE THREAD

**Issue by saeedsafavi26** [Smile-SA/gdpr-dump#84]
I get this error when I want to restore the anonymized sql file (I created using gdpr-dump tool) on database using mysql command:
ERROR 1064 (42000) at line 27: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"admin_departments" (
  "id" bigint unsigned NOT NULL AUTO_INCREMENT,
  "admin_i' at line 1

this is the command I use to restore the databse:
mysql -u <UserName> -p -h <HostAddr> db_name < dump.sql

the problem is that in the dump file, it uses double quote instead of backticks. for example:

CREATE TABLE "mytable" (
"id" bigint unsigned NOT NULL AUTO_INCREMENT,
"admin_id" bigint unsigned NOT NULL,
PRIMARY KEY ("id"),
);

**Comment by saeedsafavi26** [comment]
the problem is that in the dump file, it uses double quote instead of backticks. for example:

CREATE TABLE "mytable" (
  "id" bigint unsigned NOT NULL AUTO_INCREMENT,
  "admin_id" bigint unsigned NOT NULL,
  PRIMARY KEY ("id"),
);

**Comment by guvra** [comment]
Hi,

I don't think the issue comes from our tool, because the library that we use to create the dump file ([druidfi/mysqldump-php](https://github.com/druidfi/mysqldump-php)) is using the command `show create table` to generate the table creation statements.

cf. https://github.com/druidfi/mysqldump-php/blob/main/src/TypeAdapter/TypeAdapterMysql.php#L84

So the issue is probably from your database.
You should try to manually use a show create table query in your database to check what output it generates (e.g. `show create table admin_departments).`

But if you do find an bug with the mysqldump-php library, you'll have to create an issue on their repository, not here.

**Comment by saeedsafavi26** [comment]
Thank you for responding. 
Is there any way to set a source and destination in the config and make the process on-the-flight without creating the dump file? (read from source, anonymizing and writing to test database)
